// ===== AI HELPER (Claude API) =====
// Using var for broader compatibility
var AI = (function() {
  var API_URL_GEMINI = '/api/gemini';
  var API_URL_CLAUDE = '/api/claude';

  // Built-in dictionary for offline use
  var DICT = {
    'run': { pos: 'verb', meaning: '달리다', example: 'I run to school every day.' },
    'walk': { pos: 'verb', meaning: '걷다', example: 'I walk to the park.' },
    'eat': { pos: 'verb', meaning: '먹다', example: 'I eat breakfast every morning.' },
    'drink': { pos: 'verb', meaning: '마시다', example: 'I drink water after running.' },
    'read': { pos: 'verb', meaning: '읽다', example: 'I read a book before bed.' },
    'write': { pos: 'verb', meaning: '쓰다', example: 'I write my name on the paper.' },
    'play': { pos: 'verb', meaning: '놀다', example: 'I play with my friends.' },
    'sing': { pos: 'verb', meaning: '노래하다', example: 'She sings a happy song.' },
    'jump': { pos: 'verb', meaning: '뛰다', example: 'The frog can jump very high.' },
    'swim': { pos: 'verb', meaning: '수영하다', example: 'I swim in the pool.' },
    'think': { pos: 'verb', meaning: '생각하다', example: 'I think this is fun.' },
    'know': { pos: 'verb', meaning: '알다', example: 'I know the answer!' },
    'like': { pos: 'verb', meaning: '좋아하다', example: 'I like ice cream.' },
    'love': { pos: 'verb', meaning: '사랑하다', example: 'I love my family.' },
    'have': { pos: 'verb', meaning: '가지다', example: 'I have a pet dog.' },
    'make': { pos: 'verb', meaning: '만들다', example: 'I make a cake for mom.' },
    'go': { pos: 'verb', meaning: '가다', example: 'I go to school by bus.' },
    'come': { pos: 'verb', meaning: '오다', example: 'Come here, please!' },
    'see': { pos: 'verb', meaning: '보다', example: 'I can see the stars.' },
    'give': { pos: 'verb', meaning: '주다', example: 'I give a gift to my friend.' },
    'take': { pos: 'verb', meaning: '가져가다', example: 'Take your umbrella today.' },
    'say': { pos: 'verb', meaning: '말하다', example: 'She says hello to everyone.' },
    'tell': { pos: 'verb', meaning: '말해주다', example: 'Tell me a story, please.' },
    'help': { pos: 'verb', meaning: '돕다', example: 'I help my mom cook dinner.' },
    'try': { pos: 'verb', meaning: '시도하다', example: 'Try your best!' },
    'open': { pos: 'verb', meaning: '열다', example: 'Open the door, please.' },
    'close': { pos: 'verb', meaning: '닫다', example: 'Close your eyes and sleep.' },
    'stop': { pos: 'verb', meaning: '멈추다', example: 'Stop and look both ways.' },
    'start': { pos: 'verb', meaning: '시작하다', example: "Let's start the game!" },
    'learn': { pos: 'verb', meaning: '배우다', example: 'I learn new words every day.' },
    'study': { pos: 'verb', meaning: '공부하다', example: 'I study English after school.' },
    'draw': { pos: 'verb', meaning: '그리다', example: 'I draw a picture of my family.' },
    'sleep': { pos: 'verb', meaning: '자다', example: "I sleep at nine o'clock." },
    'wash': { pos: 'verb', meaning: '씻다', example: 'Wash your hands before eating.' },
    'cook': { pos: 'verb', meaning: '요리하다', example: 'Dad cooks dinner for us.' },
    'fly': { pos: 'verb', meaning: '날다', example: 'Birds fly in the sky.' },
    'grow': { pos: 'verb', meaning: '자라다', example: 'Plants grow in the garden.' },
    'sit': { pos: 'verb', meaning: '앉다', example: 'Please sit down.' },
    'stand': { pos: 'verb', meaning: '서다', example: 'Stand up and stretch!' },
    'watch': { pos: 'verb', meaning: '보다', example: 'I watch cartoons on Sunday.' },
    'listen': { pos: 'verb', meaning: '듣다', example: 'Listen to the music.' },
    'speak': { pos: 'verb', meaning: '말하다', example: 'I speak English and Korean.' },
    'buy': { pos: 'verb', meaning: '사다', example: 'Mom buys apples at the store.' },
    'bring': { pos: 'verb', meaning: '가져오다', example: 'Bring your book to class.' },
    'put': { pos: 'verb', meaning: '놓다', example: 'Put your shoes by the door.' },
    'hold': { pos: 'verb', meaning: '잡다', example: 'Hold my hand when we cross.' },
    'clean': { pos: 'verb', meaning: '청소하다', example: 'I clean my room on Saturday.' },
    'cat': { pos: 'noun', meaning: '고양이', example: 'The cat sleeps on the sofa.' },
    'dog': { pos: 'noun', meaning: '개', example: 'My dog likes to play fetch.' },
    'book': { pos: 'noun', meaning: '책', example: 'I read a book every night.' },
    'house': { pos: 'noun', meaning: '집', example: 'Our house has a red door.' },
    'tree': { pos: 'noun', meaning: '나무', example: 'The tree has green leaves.' },
    'school': { pos: 'noun', meaning: '학교', example: 'I go to school at eight.' },
    'friend': { pos: 'noun', meaning: '친구', example: 'My friend and I play together.' },
    'water': { pos: 'noun', meaning: '물', example: 'Drink some water!' },
    'food': { pos: 'noun', meaning: '음식', example: 'This food is delicious.' },
    'music': { pos: 'noun', meaning: '음악', example: 'I like to listen to music.' },
    'apple': { pos: 'noun', meaning: '사과', example: 'I eat an apple for snack.' },
    'ball': { pos: 'noun', meaning: '공', example: 'Throw the ball to me!' },
    'car': { pos: 'noun', meaning: '자동차', example: 'Dad drives a blue car.' },
    'door': { pos: 'noun', meaning: '문', example: 'Please close the door.' },
    'fish': { pos: 'noun', meaning: '물고기', example: 'The fish swims in the lake.' },
    'girl': { pos: 'noun', meaning: '소녀', example: 'The girl is reading a book.' },
    'boy': { pos: 'noun', meaning: '소년', example: 'The boy runs very fast.' },
    'hand': { pos: 'noun', meaning: '손', example: 'Raise your hand if you know.' },
    'head': { pos: 'noun', meaning: '머리', example: 'Put a hat on your head.' },
    'king': { pos: 'noun', meaning: '왕', example: 'The king lives in a castle.' },
    'sun': { pos: 'noun', meaning: '태양', example: 'The sun is bright today.' },
    'moon': { pos: 'noun', meaning: '달', example: 'The moon shines at night.' },
    'star': { pos: 'noun', meaning: '별', example: 'I can see a star in the sky.' },
    'rain': { pos: 'noun', meaning: '비', example: 'The rain makes flowers grow.' },
    'snow': { pos: 'noun', meaning: '눈', example: 'I play in the snow in winter.' },
    'flower': { pos: 'noun', meaning: '꽃', example: 'The flower is very pretty.' },
    'bird': { pos: 'noun', meaning: '새', example: 'A bird sits on the tree.' },
    'baby': { pos: 'noun', meaning: '아기', example: 'The baby is sleeping.' },
    'mother': { pos: 'noun', meaning: '어머니', example: 'My mother cooks great food.' },
    'father': { pos: 'noun', meaning: '아버지', example: 'My father reads me stories.' },
    'family': { pos: 'noun', meaning: '가족', example: 'I love my family.' },
    'name': { pos: 'noun', meaning: '이름', example: 'My name is Juwon.' },
    'day': { pos: 'noun', meaning: '날', example: 'Today is a beautiful day.' },
    'night': { pos: 'noun', meaning: '밤', example: 'Good night! Sleep well.' },
    'time': { pos: 'noun', meaning: '시간', example: 'What time is it now?' },
    'morning': { pos: 'noun', meaning: '아침', example: 'Good morning, everyone!' },
    'eye': { pos: 'noun', meaning: '눈(신체)', example: 'She has brown eyes.' },
    'ear': { pos: 'noun', meaning: '귀', example: 'I hear with my ears.' },
    'nose': { pos: 'noun', meaning: '코', example: 'The clown has a red nose.' },
    'mouth': { pos: 'noun', meaning: '입', example: 'Open your mouth wide.' },
    'animal': { pos: 'noun', meaning: '동물', example: 'My favorite animal is a rabbit.' },
    'color': { pos: 'noun', meaning: '색깔', example: 'What color do you like?' },
    'number': { pos: 'noun', meaning: '숫자', example: 'Pick a number from one to ten.' },
    'game': { pos: 'noun', meaning: '게임', example: "Let's play a fun game!" },
    'table': { pos: 'noun', meaning: '테이블', example: 'Put the plate on the table.' },
    'chair': { pos: 'noun', meaning: '의자', example: 'Sit on the chair, please.' },
    'bed': { pos: 'noun', meaning: '침대', example: 'I sleep in my bed.' },
    'window': { pos: 'noun', meaning: '창문', example: 'Open the window for fresh air.' },
    'teacher': { pos: 'noun', meaning: '선생님', example: 'Our teacher is very kind.' },
    'big': { pos: 'adjective', meaning: '큰', example: 'The elephant is very big.' },
    'small': { pos: 'adjective', meaning: '작은', example: 'The ant is very small.' },
    'happy': { pos: 'adjective', meaning: '행복한', example: 'I am happy today!' },
    'sad': { pos: 'adjective', meaning: '슬픈', example: 'The puppy looks sad.' },
    'good': { pos: 'adjective', meaning: '좋은', example: 'You did a good job!' },
    'bad': { pos: 'adjective', meaning: '나쁜', example: 'Rainy weather is not bad.' },
    'new': { pos: 'adjective', meaning: '새로운', example: 'I have new shoes.' },
    'old': { pos: 'adjective', meaning: '오래된', example: 'This is an old book.' },
    'fast': { pos: 'adjective', meaning: '빠른', example: 'The rabbit is very fast.' },
    'slow': { pos: 'adjective', meaning: '느린', example: 'The turtle is slow but steady.' },
    'hot': { pos: 'adjective', meaning: '뜨거운', example: 'The soup is very hot.' },
    'cold': { pos: 'adjective', meaning: '차가운', example: 'It is cold in winter.' },
    'tall': { pos: 'adjective', meaning: '키가 큰', example: 'The giraffe is very tall.' },
    'short': { pos: 'adjective', meaning: '짧은', example: 'I have short hair.' },
    'long': { pos: 'adjective', meaning: '긴', example: 'The snake is very long.' },
    'red': { pos: 'adjective', meaning: '빨간', example: 'I have a red backpack.' },
    'blue': { pos: 'adjective', meaning: '파란', example: 'The sky is blue.' },
    'green': { pos: 'adjective', meaning: '초록', example: 'The grass is green.' },
    'yellow': { pos: 'adjective', meaning: '노란', example: 'The banana is yellow.' },
    'white': { pos: 'adjective', meaning: '하얀', example: 'Snow is white.' },
    'black': { pos: 'adjective', meaning: '검은', example: 'My cat is black.' },
    'pretty': { pos: 'adjective', meaning: '예쁜', example: 'The flowers are pretty.' },
    'beautiful': { pos: 'adjective', meaning: '아름다운', example: 'What a beautiful sunset!' },
    'strong': { pos: 'adjective', meaning: '강한', example: 'The lion is strong.' },
    'brave': { pos: 'adjective', meaning: '용감한', example: 'You are very brave!' },
    'kind': { pos: 'adjective', meaning: '친절한', example: 'She is a kind person.' },
    'funny': { pos: 'adjective', meaning: '웃긴', example: 'The movie was so funny!' },
    'hungry': { pos: 'adjective', meaning: '배고픈', example: 'I am hungry for lunch.' },
    'tired': { pos: 'adjective', meaning: '피곤한', example: 'I feel tired after running.' },
    'dirty': { pos: 'adjective', meaning: '더러운', example: 'My shoes are dirty.' },
    'quiet': { pos: 'adjective', meaning: '조용한', example: 'The library is quiet.' },
    'loud': { pos: 'adjective', meaning: '시끄러운', example: 'The music is too loud.' },
    'sweet': { pos: 'adjective', meaning: '달콤한', example: 'Candy is sweet.' },
    'soft': { pos: 'adjective', meaning: '부드러운', example: 'The pillow is soft.' },
    'hard': { pos: 'adjective', meaning: '단단한', example: 'The rock is hard.' },
    'bright': { pos: 'adjective', meaning: '밝은', example: 'The sun is bright.' },
    'dark': { pos: 'adjective', meaning: '어두운', example: 'It is dark at night.' },
    'easy': { pos: 'adjective', meaning: '쉬운', example: 'This game is easy and fun!' },
    'difficult': { pos: 'adjective', meaning: '어려운', example: 'The puzzle is difficult.' },
    'important': { pos: 'adjective', meaning: '중요한', example: 'Homework is important.' },
    'special': { pos: 'adjective', meaning: '특별한', example: 'Today is a special day!' },
    'very': { pos: 'adverb', meaning: '매우', example: 'The cake is very good.' },
    'quickly': { pos: 'adverb', meaning: '빠르게', example: 'He runs quickly.' },
    'slowly': { pos: 'adverb', meaning: '느리게', example: 'Walk slowly on the ice.' },
    'always': { pos: 'adverb', meaning: '항상', example: 'I always brush my teeth.' },
    'never': { pos: 'adverb', meaning: '절대 안 하다', example: 'I never skip breakfast.' },
    'often': { pos: 'adverb', meaning: '자주', example: 'We often go to the park.' },
    'really': { pos: 'adverb', meaning: '정말', example: 'I really like this song.' },
    'well': { pos: 'adverb', meaning: '잘', example: 'She sings very well.' },
    'also': { pos: 'adverb', meaning: '또한', example: 'I also like pizza.' },
    'just': { pos: 'adverb', meaning: '그냥, 막', example: 'I just finished my homework.' },
    'still': { pos: 'adverb', meaning: '아직', example: 'I am still reading.' },
    'already': { pos: 'adverb', meaning: '이미', example: 'I already ate lunch.' },
    'together': { pos: 'adverb', meaning: '함께', example: "Let's play together!" },
    'again': { pos: 'adverb', meaning: '다시', example: "Let's try again!" },
    'here': { pos: 'adverb', meaning: '여기', example: 'Come here, please.' },
    'there': { pos: 'adverb', meaning: '거기', example: 'The ball is over there.' },
    'today': { pos: 'adverb', meaning: '오늘', example: 'I feel great today!' },
    'tomorrow': { pos: 'adverb', meaning: '내일', example: 'We have a test tomorrow.' },
    'yesterday': { pos: 'adverb', meaning: '어제', example: 'I went to the zoo yesterday.' },
    'outside': { pos: 'adverb', meaning: '밖에서', example: "Let's play outside!" },
    'inside': { pos: 'adverb', meaning: '안에서', example: 'Stay inside when it rains.' },
    // ===== BODY PARTS =====
    'leg': { pos: 'noun', meaning: '다리', example: 'I hurt my leg playing soccer.' },
    'arm': { pos: 'noun', meaning: '팔', example: 'She raised her arm in class.' },
    'finger': { pos: 'noun', meaning: '손가락', example: 'I count with my fingers.' },
    'toe': { pos: 'noun', meaning: '발가락', example: 'I wiggle my toes in the sand.' },
    'tooth': { pos: 'noun', meaning: '이', example: 'I lost a tooth today!' },
    'hair': { pos: 'noun', meaning: '머리카락', example: 'She has long brown hair.' },
    'face': { pos: 'noun', meaning: '얼굴', example: 'Wash your face every morning.' },
    'shoulder': { pos: 'noun', meaning: '어깨', example: 'The bird sat on my shoulder.' },
    'knee': { pos: 'noun', meaning: '무릎', example: 'I fell and hurt my knee.' },
    'stomach': { pos: 'noun', meaning: '배', example: 'My stomach is growling.' },
    'neck': { pos: 'noun', meaning: '목', example: 'The giraffe has a long neck.' },
    'lip': { pos: 'noun', meaning: '입술', example: 'She put on pink lip balm.' },
    'tongue': { pos: 'noun', meaning: '혀', example: 'The ice cream is cold on my tongue.' },
    'skin': { pos: 'noun', meaning: '피부', example: 'Put sunscreen on your skin.' },
    'bone': { pos: 'noun', meaning: '뼈', example: 'The dog loves to chew a bone.' },
    'heart': { pos: 'noun', meaning: '심장', example: 'My heart beats fast when I run.' },
    'brain': { pos: 'noun', meaning: '뇌', example: 'We use our brain to think.' },
    'chest': { pos: 'noun', meaning: '가슴', example: 'Take a deep breath into your chest.' },
    'elbow': { pos: 'noun', meaning: '팔꿈치', example: 'I bumped my elbow on the table.' },
    'thumb': { pos: 'noun', meaning: '엄지', example: 'Give me a thumbs up!' },
    // ===== FAMILY =====
    'brother': { pos: 'noun', meaning: '형/오빠/남동생', example: 'My brother plays with me.' },
    'sister': { pos: 'noun', meaning: '언니/누나/여동생', example: 'My sister reads me stories.' },
    'grandma': { pos: 'noun', meaning: '할머니', example: 'Grandma makes the best cookies.' },
    'grandpa': { pos: 'noun', meaning: '할아버지', example: 'Grandpa tells funny stories.' },
    'uncle': { pos: 'noun', meaning: '삼촌', example: 'My uncle lives far away.' },
    'aunt': { pos: 'noun', meaning: '이모/고모', example: 'My aunt gave me a gift.' },
    'cousin': { pos: 'noun', meaning: '사촌', example: 'I play with my cousin on weekends.' },
    'parent': { pos: 'noun', meaning: '부모', example: 'My parents love me very much.' },
    'son': { pos: 'noun', meaning: '아들', example: 'He is a kind son.' },
    'daughter': { pos: 'noun', meaning: '딸', example: 'She is a smart daughter.' },
    // ===== ANIMALS =====
    'rabbit': { pos: 'noun', meaning: '토끼', example: 'The rabbit hops in the garden.' },
    'bear': { pos: 'noun', meaning: '곰', example: 'The bear sleeps in winter.' },
    'lion': { pos: 'noun', meaning: '사자', example: 'The lion is the king of animals.' },
    'tiger': { pos: 'noun', meaning: '호랑이', example: 'The tiger has orange stripes.' },
    'elephant': { pos: 'noun', meaning: '코끼리', example: 'The elephant has a long trunk.' },
    'monkey': { pos: 'noun', meaning: '원숭이', example: 'The monkey climbs the tree.' },
    'horse': { pos: 'noun', meaning: '말', example: 'I want to ride a horse.' },
    'cow': { pos: 'noun', meaning: '소', example: 'The cow gives us milk.' },
    'pig': { pos: 'noun', meaning: '돼지', example: 'The pig plays in the mud.' },
    'sheep': { pos: 'noun', meaning: '양', example: 'The sheep has soft wool.' },
    'chicken': { pos: 'noun', meaning: '닭', example: 'The chicken lays eggs.' },
    'duck': { pos: 'noun', meaning: '오리', example: 'The duck swims in the pond.' },
    'frog': { pos: 'noun', meaning: '개구리', example: 'The frog jumps into the water.' },
    'snake': { pos: 'noun', meaning: '뱀', example: 'The snake moves without legs.' },
    'mouse': { pos: 'noun', meaning: '쥐', example: 'The mouse likes cheese.' },
    'deer': { pos: 'noun', meaning: '사슴', example: 'The deer runs in the forest.' },
    'whale': { pos: 'noun', meaning: '고래', example: 'The whale is very big.' },
    'dolphin': { pos: 'noun', meaning: '돌고래', example: 'The dolphin jumps out of the water.' },
    'butterfly': { pos: 'noun', meaning: '나비', example: 'The butterfly has pretty wings.' },
    'bee': { pos: 'noun', meaning: '벌', example: 'The bee makes honey.' },
    'ant': { pos: 'noun', meaning: '개미', example: 'The ant carries food to its home.' },
    'spider': { pos: 'noun', meaning: '거미', example: 'The spider makes a web.' },
    'turtle': { pos: 'noun', meaning: '거북이', example: 'The turtle moves very slowly.' },
    'penguin': { pos: 'noun', meaning: '펭귄', example: 'The penguin lives in the cold.' },
    'parrot': { pos: 'noun', meaning: '앵무새', example: 'The parrot can talk like us.' },
    'shark': { pos: 'noun', meaning: '상어', example: 'The shark has sharp teeth.' },
    'zebra': { pos: 'noun', meaning: '얼룩말', example: 'The zebra has black and white stripes.' },
    'giraffe': { pos: 'noun', meaning: '기린', example: 'The giraffe eats leaves from tall trees.' },
    'fox': { pos: 'noun', meaning: '여우', example: 'The fox is clever and fast.' },
    'wolf': { pos: 'noun', meaning: '늑대', example: 'The wolf howls at the moon.' },
    'owl': { pos: 'noun', meaning: '올빼미', example: 'The owl comes out at night.' },
    'eagle': { pos: 'noun', meaning: '독수리', example: 'The eagle flies very high.' },
    'crab': { pos: 'noun', meaning: '게', example: 'The crab walks sideways on the beach.' },
    'goat': { pos: 'noun', meaning: '염소', example: 'The goat climbs the mountain.' },
    'bug': { pos: 'noun', meaning: '벌레', example: 'I found a bug in the garden.' },
    'worm': { pos: 'noun', meaning: '벌레/지렁이', example: 'The bird eats a worm.' },
    // ===== FOOD & DRINK =====
    'bread': { pos: 'noun', meaning: '빵', example: 'I eat bread for breakfast.' },
    'rice': { pos: 'noun', meaning: '쌀/밥', example: 'We eat rice every day.' },
    'milk': { pos: 'noun', meaning: '우유', example: 'I drink milk in the morning.' },
    'juice': { pos: 'noun', meaning: '주스', example: 'I like orange juice.' },
    'cake': { pos: 'noun', meaning: '케이크', example: 'We eat cake on birthdays.' },
    'cookie': { pos: 'noun', meaning: '쿠키', example: 'Mom baked chocolate cookies.' },
    'cheese': { pos: 'noun', meaning: '치즈', example: 'I put cheese on my sandwich.' },
    'egg': { pos: 'noun', meaning: '달걀', example: 'I eat eggs for breakfast.' },
    'meat': { pos: 'noun', meaning: '고기', example: 'Dad grills meat for dinner.' },
    'pizza': { pos: 'noun', meaning: '피자', example: 'I love eating pizza.' },
    'noodle': { pos: 'noun', meaning: '국수/면', example: 'I eat noodles with chopsticks.' },
    'soup': { pos: 'noun', meaning: '국/수프', example: 'The soup is hot and yummy.' },
    'salad': { pos: 'noun', meaning: '샐러드', example: 'I eat salad with my lunch.' },
    'chocolate': { pos: 'noun', meaning: '초콜릿', example: 'I love chocolate ice cream.' },
    'candy': { pos: 'noun', meaning: '사탕', example: 'I got candy on Halloween.' },
    'fruit': { pos: 'noun', meaning: '과일', example: 'Fruit is good for you.' },
    'vegetable': { pos: 'noun', meaning: '채소', example: 'Eat your vegetables!' },
    'banana': { pos: 'noun', meaning: '바나나', example: 'The banana is yellow.' },
    'grape': { pos: 'noun', meaning: '포도', example: 'I like to eat grapes.' },
    'strawberry': { pos: 'noun', meaning: '딸기', example: 'Strawberries are red and sweet.' },
    'watermelon': { pos: 'noun', meaning: '수박', example: 'We eat watermelon in summer.' },
    'tomato': { pos: 'noun', meaning: '토마토', example: 'The tomato is red and round.' },
    'potato': { pos: 'noun', meaning: '감자', example: 'I like baked potatoes.' },
    'carrot': { pos: 'noun', meaning: '당근', example: 'Rabbits like to eat carrots.' },
    'onion': { pos: 'noun', meaning: '양파', example: 'Onions can make you cry.' },
    'corn': { pos: 'noun', meaning: '옥수수', example: 'I eat corn on the cob.' },
    'sandwich': { pos: 'noun', meaning: '샌드위치', example: 'I made a ham sandwich.' },
    'hamburger': { pos: 'noun', meaning: '햄버거', example: 'I ate a big hamburger.' },
    'butter': { pos: 'noun', meaning: '버터', example: 'Put butter on the bread.' },
    'sugar': { pos: 'noun', meaning: '설탕', example: 'Too much sugar is not good.' },
    'salt': { pos: 'noun', meaning: '소금', example: 'Add a little salt to the soup.' },
    'pepper': { pos: 'noun', meaning: '후추', example: 'Pepper makes me sneeze.' },
    'honey': { pos: 'noun', meaning: '꿀', example: 'Bees make sweet honey.' },
    'pie': { pos: 'noun', meaning: '파이', example: 'Grandma baked an apple pie.' },
    'tea': { pos: 'noun', meaning: '차', example: 'Mom drinks hot tea.' },
    'cereal': { pos: 'noun', meaning: '시리얼', example: 'I eat cereal with milk.' },
    'pancake': { pos: 'noun', meaning: '팬케이크', example: 'We make pancakes on Sunday.' },
    'popcorn': { pos: 'noun', meaning: '팝콘', example: 'We eat popcorn at the movies.' },
    // ===== SCHOOL =====
    'pen': { pos: 'noun', meaning: '펜', example: 'I write with a blue pen.' },
    'pencil': { pos: 'noun', meaning: '연필', example: 'Sharpen your pencil.' },
    'eraser': { pos: 'noun', meaning: '지우개', example: 'I need an eraser.' },
    'notebook': { pos: 'noun', meaning: '공책', example: 'Write it in your notebook.' },
    'desk': { pos: 'noun', meaning: '책상', example: 'My desk is near the window.' },
    'classroom': { pos: 'noun', meaning: '교실', example: 'Our classroom is on the second floor.' },
    'homework': { pos: 'noun', meaning: '숙제', example: 'I finished my homework.' },
    'test': { pos: 'noun', meaning: '시험', example: 'We have a math test today.' },
    'math': { pos: 'noun', meaning: '수학', example: 'I like math class.' },
    'science': { pos: 'noun', meaning: '과학', example: 'Science is interesting.' },
    'student': { pos: 'noun', meaning: '학생', example: 'She is a good student.' },
    'lesson': { pos: 'noun', meaning: '수업', example: 'The lesson was fun today.' },
    'ruler': { pos: 'noun', meaning: '자', example: 'Use a ruler to draw a line.' },
    'crayon': { pos: 'noun', meaning: '크레파스', example: 'I color with crayons.' },
    'paper': { pos: 'noun', meaning: '종이', example: 'I need a piece of paper.' },
    'backpack': { pos: 'noun', meaning: '가방/배낭', example: 'My backpack is heavy today.' },
    'library': { pos: 'noun', meaning: '도서관', example: 'I borrow books from the library.' },
    'board': { pos: 'noun', meaning: '칠판', example: 'The teacher writes on the board.' },
    'chalk': { pos: 'noun', meaning: '분필', example: 'The teacher uses chalk.' },
    'grade': { pos: 'noun', meaning: '성적/학년', example: 'I got a good grade.' },
    'prize': { pos: 'noun', meaning: '상', example: 'She won first prize.' },
    // ===== NATURE =====
    'river': { pos: 'noun', meaning: '강', example: 'The river flows to the sea.' },
    'lake': { pos: 'noun', meaning: '호수', example: 'We swim in the lake.' },
    'ocean': { pos: 'noun', meaning: '바다', example: 'The ocean is very deep.' },
    'sea': { pos: 'noun', meaning: '바다', example: 'I love the sea!' },
    'mountain': { pos: 'noun', meaning: '산', example: 'We climbed the mountain.' },
    'forest': { pos: 'noun', meaning: '숲', example: 'Many animals live in the forest.' },
    'garden': { pos: 'noun', meaning: '정원', example: 'We grow flowers in the garden.' },
    'grass': { pos: 'noun', meaning: '잔디/풀', example: 'The grass is green.' },
    'leaf': { pos: 'noun', meaning: '잎', example: 'The leaf fell from the tree.' },
    'rock': { pos: 'noun', meaning: '바위', example: 'I sat on a big rock.' },
    'sand': { pos: 'noun', meaning: '모래', example: 'I build a castle in the sand.' },
    'sky': { pos: 'noun', meaning: '하늘', example: 'The sky is blue today.' },
    'cloud': { pos: 'noun', meaning: '구름', example: 'The clouds look like cotton.' },
    'wind': { pos: 'noun', meaning: '바람', example: 'The wind blows my hat away.' },
    'weather': { pos: 'noun', meaning: '날씨', example: 'The weather is nice today.' },
    'island': { pos: 'noun', meaning: '섬', example: 'We took a boat to the island.' },
    'desert': { pos: 'noun', meaning: '사막', example: 'The desert is very hot and dry.' },
    'hill': { pos: 'noun', meaning: '언덕', example: 'We ran up the hill.' },
    'field': { pos: 'noun', meaning: '들판', example: 'Cows eat grass in the field.' },
    'beach': { pos: 'noun', meaning: '해변', example: 'We play on the beach.' },
    'earth': { pos: 'noun', meaning: '지구', example: 'The earth goes around the sun.' },
    'world': { pos: 'noun', meaning: '세계', example: 'There are many countries in the world.' },
    'land': { pos: 'noun', meaning: '땅', example: 'The bird landed on the land.' },
    'ice': { pos: 'noun', meaning: '얼음', example: 'Be careful, the ice is slippery.' },
    'fire': { pos: 'noun', meaning: '불', example: 'We sit around the fire.' },
    'stone': { pos: 'noun', meaning: '돌', example: 'I threw a stone into the lake.' },
    'mud': { pos: 'noun', meaning: '진흙', example: 'My shoes are covered in mud.' },
    'rainbow': { pos: 'noun', meaning: '무지개', example: 'I see a rainbow after the rain.' },
    // ===== CLOTHES =====
    'shirt': { pos: 'noun', meaning: '셔츠', example: 'I wear a white shirt to school.' },
    'pants': { pos: 'noun', meaning: '바지', example: 'My pants are too long.' },
    'shoes': { pos: 'noun', meaning: '신발', example: 'Put on your shoes.' },
    'hat': { pos: 'noun', meaning: '모자', example: 'I wear a hat in the sun.' },
    'jacket': { pos: 'noun', meaning: '자켓', example: 'Wear your jacket, it is cold.' },
    'dress': { pos: 'noun', meaning: '원피스', example: 'She wears a pretty dress.' },
    'socks': { pos: 'noun', meaning: '양말', example: 'I wear warm socks in winter.' },
    'coat': { pos: 'noun', meaning: '코트', example: 'Put on your coat before you go out.' },
    'gloves': { pos: 'noun', meaning: '장갑', example: 'I wear gloves when it snows.' },
    'scarf': { pos: 'noun', meaning: '목도리', example: 'The scarf keeps my neck warm.' },
    'uniform': { pos: 'noun', meaning: '교복/유니폼', example: 'I wear a uniform to school.' },
    'pocket': { pos: 'noun', meaning: '주머니', example: 'I put my hands in my pockets.' },
    'boot': { pos: 'noun', meaning: '부츠', example: 'I wear boots in the rain.' },
    'sweater': { pos: 'noun', meaning: '스웨터', example: 'My sweater is so warm.' },
    'skirt': { pos: 'noun', meaning: '치마', example: 'She wears a blue skirt.' },
    'glasses': { pos: 'noun', meaning: '안경', example: 'I wear glasses to read.' },
    'ring': { pos: 'noun', meaning: '반지', example: 'Mom has a gold ring.' },
    // ===== HOUSE & HOME =====
    'room': { pos: 'noun', meaning: '방', example: 'Clean your room, please.' },
    'kitchen': { pos: 'noun', meaning: '부엌', example: 'Mom is cooking in the kitchen.' },
    'bathroom': { pos: 'noun', meaning: '화장실', example: 'Wash your hands in the bathroom.' },
    'bedroom': { pos: 'noun', meaning: '침실', example: 'I sleep in my bedroom.' },
    'floor': { pos: 'noun', meaning: '바닥', example: 'Do not sit on the cold floor.' },
    'wall': { pos: 'noun', meaning: '벽', example: 'I put a picture on the wall.' },
    'roof': { pos: 'noun', meaning: '지붕', example: 'The cat is on the roof.' },
    'stairs': { pos: 'noun', meaning: '계단', example: 'Walk carefully on the stairs.' },
    'yard': { pos: 'noun', meaning: '마당', example: 'I play in the yard.' },
    'fence': { pos: 'noun', meaning: '울타리', example: 'The dog cannot jump over the fence.' },
    'gate': { pos: 'noun', meaning: '문/대문', example: 'Close the gate, please.' },
    'key': { pos: 'noun', meaning: '열쇠', example: 'I lost my house key.' },
    'shelf': { pos: 'noun', meaning: '선반', example: 'The books are on the shelf.' },
    'lamp': { pos: 'noun', meaning: '램프', example: 'Turn on the lamp, please.' },
    'mirror': { pos: 'noun', meaning: '거울', example: 'I look in the mirror.' },
    'carpet': { pos: 'noun', meaning: '카펫', example: 'The carpet is soft and warm.' },
    'curtain': { pos: 'noun', meaning: '커튼', example: 'Open the curtain for sunlight.' },
    'towel': { pos: 'noun', meaning: '수건', example: 'Dry your hands with a towel.' },
    'soap': { pos: 'noun', meaning: '비누', example: 'Wash your hands with soap.' },
    'blanket': { pos: 'noun', meaning: '담요', example: 'I sleep with a warm blanket.' },
    'pillow': { pos: 'noun', meaning: '베개', example: 'My pillow is very soft.' },
    'shower': { pos: 'noun', meaning: '샤워', example: 'I take a shower every evening.' },
    // ===== PLACES =====
    'park': { pos: 'noun', meaning: '공원', example: 'We play in the park.' },
    'store': { pos: 'noun', meaning: '가게', example: 'We buy food at the store.' },
    'hospital': { pos: 'noun', meaning: '병원', example: 'The doctor works at the hospital.' },
    'restaurant': { pos: 'noun', meaning: '식당', example: 'We eat dinner at a restaurant.' },
    'airport': { pos: 'noun', meaning: '공항', example: 'We go to the airport to fly.' },
    'museum': { pos: 'noun', meaning: '박물관', example: 'We saw dinosaurs at the museum.' },
    'church': { pos: 'noun', meaning: '교회', example: 'We go to church on Sunday.' },
    'farm': { pos: 'noun', meaning: '농장', example: 'The farm has many animals.' },
    'city': { pos: 'noun', meaning: '도시', example: 'The city has tall buildings.' },
    'town': { pos: 'noun', meaning: '마을', example: 'Our town is small and quiet.' },
    'village': { pos: 'noun', meaning: '시골 마을', example: 'Grandma lives in a village.' },
    'country': { pos: 'noun', meaning: '나라', example: 'Korea is a beautiful country.' },
    'bridge': { pos: 'noun', meaning: '다리', example: 'We walk across the bridge.' },
    'road': { pos: 'noun', meaning: '도로', example: 'Look both ways before crossing the road.' },
    'street': { pos: 'noun', meaning: '거리', example: 'Our street has many trees.' },
    'market': { pos: 'noun', meaning: '시장', example: 'We buy fruit at the market.' },
    'hotel': { pos: 'noun', meaning: '호텔', example: 'We stay at a hotel on vacation.' },
    'pool': { pos: 'noun', meaning: '수영장', example: 'I swim in the pool.' },
    'zoo': { pos: 'noun', meaning: '동물원', example: 'We saw lions at the zoo.' },
    'station': { pos: 'noun', meaning: '역', example: 'We wait at the bus station.' },
    'office': { pos: 'noun', meaning: '사무실', example: 'Dad works in an office.' },
    'palace': { pos: 'noun', meaning: '궁전', example: 'The king lives in a palace.' },
    'castle': { pos: 'noun', meaning: '성', example: 'The castle is on top of the hill.' },
    // ===== THINGS & OBJECTS =====
    'phone': { pos: 'noun', meaning: '전화기', example: 'Mom is talking on the phone.' },
    'computer': { pos: 'noun', meaning: '컴퓨터', example: 'I use the computer for homework.' },
    'television': { pos: 'noun', meaning: '텔레비전', example: 'We watch television after dinner.' },
    'camera': { pos: 'noun', meaning: '카메라', example: 'I take photos with my camera.' },
    'clock': { pos: 'noun', meaning: '시계', example: 'The clock says it is three.' },
    'cup': { pos: 'noun', meaning: '컵', example: 'I drink water from a cup.' },
    'plate': { pos: 'noun', meaning: '접시', example: 'Put the food on the plate.' },
    'bowl': { pos: 'noun', meaning: '그릇', example: 'I eat soup from a bowl.' },
    'spoon': { pos: 'noun', meaning: '숟가락', example: 'I eat cereal with a spoon.' },
    'fork': { pos: 'noun', meaning: '포크', example: 'I eat salad with a fork.' },
    'knife': { pos: 'noun', meaning: '칼', example: 'Be careful with the knife.' },
    'bottle': { pos: 'noun', meaning: '병', example: 'I drink water from a bottle.' },
    'toy': { pos: 'noun', meaning: '장난감', example: 'I play with my toys.' },
    'gift': { pos: 'noun', meaning: '선물', example: 'I got a gift for my birthday.' },
    'money': { pos: 'noun', meaning: '돈', example: 'I saved my money.' },
    'coin': { pos: 'noun', meaning: '동전', example: 'I found a coin on the ground.' },
    'ticket': { pos: 'noun', meaning: '표', example: 'We need tickets for the movie.' },
    'map': { pos: 'noun', meaning: '지도', example: 'We use a map to find the way.' },
    'flag': { pos: 'noun', meaning: '깃발', example: 'The flag is red, white, and blue.' },
    'bell': { pos: 'noun', meaning: '종', example: 'The school bell rings at nine.' },
    'candle': { pos: 'noun', meaning: '촛불', example: 'I blew out the candles on my cake.' },
    'umbrella': { pos: 'noun', meaning: '우산', example: 'Take your umbrella, it will rain.' },
    'basket': { pos: 'noun', meaning: '바구니', example: 'Put the apples in the basket.' },
    'brush': { pos: 'noun', meaning: '솔/브러시', example: 'I use a brush for my hair.' },
    'box': { pos: 'noun', meaning: '상자', example: 'The cat is hiding in the box.' },
    'bag': { pos: 'noun', meaning: '가방', example: 'I put my lunch in my bag.' },
    'wheel': { pos: 'noun', meaning: '바퀴', example: 'The car has four wheels.' },
    'rope': { pos: 'noun', meaning: '줄/밧줄', example: 'We jump rope at recess.' },
    'letter': { pos: 'noun', meaning: '편지', example: 'I wrote a letter to my friend.' },
    'sign': { pos: 'noun', meaning: '표지판', example: 'The sign says stop.' },
    'picture': { pos: 'noun', meaning: '그림', example: 'I drew a picture of my family.' },
    'photo': { pos: 'noun', meaning: '사진', example: 'We took a family photo.' },
    'robot': { pos: 'noun', meaning: '로봇', example: 'I want a toy robot.' },
    'rocket': { pos: 'noun', meaning: '로켓', example: 'The rocket flies to space.' },
    'sticker': { pos: 'noun', meaning: '스티커', example: 'I collect stickers.' },
    // ===== TIME =====
    'week': { pos: 'noun', meaning: '주', example: 'There are seven days in a week.' },
    'month': { pos: 'noun', meaning: '월/달', example: 'My birthday is next month.' },
    'year': { pos: 'noun', meaning: '년/해', example: 'I am eight years old.' },
    'spring': { pos: 'noun', meaning: '봄', example: 'Flowers bloom in spring.' },
    'summer': { pos: 'noun', meaning: '여름', example: 'I swim a lot in summer.' },
    'winter': { pos: 'noun', meaning: '겨울', example: 'It snows in winter.' },
    'birthday': { pos: 'noun', meaning: '생일', example: 'Happy birthday to you!' },
    'holiday': { pos: 'noun', meaning: '공휴일', example: 'We have no school on holidays.' },
    'vacation': { pos: 'noun', meaning: '방학/휴가', example: 'We go to the beach on vacation.' },
    'hour': { pos: 'noun', meaning: '시간', example: 'The movie is two hours long.' },
    'minute': { pos: 'noun', meaning: '분', example: 'Wait five minutes, please.' },
    'second': { pos: 'noun', meaning: '초', example: 'It took only ten seconds!' },
    'weekend': { pos: 'noun', meaning: '주말', example: 'I play all weekend.' },
    'season': { pos: 'noun', meaning: '계절', example: 'My favorite season is fall.' },
    // ===== CONCEPTS =====
    'idea': { pos: 'noun', meaning: '생각/아이디어', example: 'I have a great idea!' },
    'question': { pos: 'noun', meaning: '질문', example: 'Can I ask a question?' },
    'answer': { pos: 'noun', meaning: '답', example: 'I know the answer!' },
    'problem': { pos: 'noun', meaning: '문제', example: 'This math problem is hard.' },
    'story': { pos: 'noun', meaning: '이야기', example: 'Tell me a bedtime story.' },
    'song': { pos: 'noun', meaning: '노래', example: 'I like this song.' },
    'dream': { pos: 'noun', meaning: '꿈', example: 'I had a nice dream.' },
    'wish': { pos: 'noun', meaning: '소원', example: 'Make a wish on a star!' },
    'secret': { pos: 'noun', meaning: '비밀', example: 'Can you keep a secret?' },
    'surprise': { pos: 'noun', meaning: '깜짝', example: 'We planned a surprise party.' },
    'joke': { pos: 'noun', meaning: '농담', example: 'He told a funny joke.' },
    'mistake': { pos: 'noun', meaning: '실수', example: 'It is okay to make mistakes.' },
    'rule': { pos: 'noun', meaning: '규칙', example: 'We follow the rules at school.' },
    'team': { pos: 'noun', meaning: '팀', example: 'Our team won the game!' },
    'group': { pos: 'noun', meaning: '그룹', example: 'We work in a group.' },
    'part': { pos: 'noun', meaning: '부분', example: 'This is my favorite part.' },
    'piece': { pos: 'noun', meaning: '조각', example: 'Can I have a piece of cake?' },
    'side': { pos: 'noun', meaning: '옆/면', example: 'Stand on this side.' },
    'top': { pos: 'noun', meaning: '꼭대기', example: 'The cat is on top of the tree.' },
    'bottom': { pos: 'noun', meaning: '바닥/아래', example: 'The toy is at the bottom of the box.' },
    'middle': { pos: 'noun', meaning: '가운데', example: 'I sit in the middle.' },
    'end': { pos: 'noun', meaning: '끝', example: 'This is the end of the story.' },
    'beginning': { pos: 'noun', meaning: '시작', example: 'Read from the beginning.' },
    'truth': { pos: 'noun', meaning: '진실', example: 'Always tell the truth.' },
    'peace': { pos: 'noun', meaning: '평화', example: 'I wish for world peace.' },
    'power': { pos: 'noun', meaning: '힘', example: 'The superhero has great power.' },
    'luck': { pos: 'noun', meaning: '행운', example: 'Good luck on your test!' },
    'magic': { pos: 'noun', meaning: '마법', example: 'The wizard does magic tricks.' },
    'hope': { pos: 'noun', meaning: '희망', example: 'I hope we win the game.' },
    'danger': { pos: 'noun', meaning: '위험', example: 'Stay away from danger.' },
    'noise': { pos: 'noun', meaning: '소음', example: 'What is that loud noise?' },
    'silence': { pos: 'noun', meaning: '침묵', example: 'There was silence in the room.' },
    'life': { pos: 'noun', meaning: '삶/생명', example: 'I love my life.' },
    'age': { pos: 'noun', meaning: '나이', example: 'What age are you?' },
    'shape': { pos: 'noun', meaning: '모양', example: 'A ball is a round shape.' },
    'space': { pos: 'noun', meaning: '우주/공간', example: 'I want to go to space.' },
    'place': { pos: 'noun', meaning: '장소', example: 'This is a nice place.' },
    'way': { pos: 'noun', meaning: '길/방법', example: 'Which way is the park?' },
    'reason': { pos: 'noun', meaning: '이유', example: 'Tell me the reason why.' },
    // ===== PEOPLE =====
    'person': { pos: 'noun', meaning: '사람', example: 'She is a nice person.' },
    'people': { pos: 'noun', meaning: '사람들', example: 'Many people are in the park.' },
    'child': { pos: 'noun', meaning: '아이', example: 'Every child likes to play.' },
    'man': { pos: 'noun', meaning: '남자', example: 'The man is very tall.' },
    'woman': { pos: 'noun', meaning: '여자', example: 'The woman is a doctor.' },
    'doctor': { pos: 'noun', meaning: '의사', example: 'The doctor helps sick people.' },
    'nurse': { pos: 'noun', meaning: '간호사', example: 'The nurse takes care of us.' },
    'police': { pos: 'noun', meaning: '경찰', example: 'The police keep us safe.' },
    'farmer': { pos: 'noun', meaning: '농부', example: 'The farmer grows vegetables.' },
    'singer': { pos: 'noun', meaning: '가수', example: 'The singer has a beautiful voice.' },
    'player': { pos: 'noun', meaning: '선수', example: 'He is a great soccer player.' },
    'driver': { pos: 'noun', meaning: '운전사', example: 'The bus driver is friendly.' },
    'worker': { pos: 'noun', meaning: '일꾼/근로자', example: 'The workers build the house.' },
    'neighbor': { pos: 'noun', meaning: '이웃', example: 'Our neighbor has a cute dog.' },
    'hero': { pos: 'noun', meaning: '영웅', example: 'The firefighter is a hero.' },
    'princess': { pos: 'noun', meaning: '공주', example: 'The princess lives in the castle.' },
    'prince': { pos: 'noun', meaning: '왕자', example: 'The prince rides a white horse.' },
    'queen': { pos: 'noun', meaning: '여왕', example: 'The queen wears a crown.' },
    'soldier': { pos: 'noun', meaning: '군인', example: 'The soldier is very brave.' },
    'pilot': { pos: 'noun', meaning: '조종사', example: 'The pilot flies the airplane.' },
    'chef': { pos: 'noun', meaning: '요리사', example: 'The chef makes delicious food.' },
    'artist': { pos: 'noun', meaning: '예술가', example: 'The artist paints pictures.' },
    'dentist': { pos: 'noun', meaning: '치과의사', example: 'I visit the dentist twice a year.' },
    'scientist': { pos: 'noun', meaning: '과학자', example: 'The scientist does experiments.' },
    // ===== MORE VERBS =====
    'climb': { pos: 'verb', meaning: '오르다', example: 'I climb the tree.' },
    'dance': { pos: 'verb', meaning: '춤추다', example: 'I like to dance to music.' },
    'fall': { pos: 'verb', meaning: '넘어지다/떨어지다', example: 'Be careful, do not fall!' },
    'kick': { pos: 'verb', meaning: '차다', example: 'I kick the soccer ball.' },
    'pull': { pos: 'verb', meaning: '당기다', example: 'Pull the door to open it.' },
    'push': { pos: 'verb', meaning: '밀다', example: 'Push the button to start.' },
    'throw': { pos: 'verb', meaning: '던지다', example: 'Throw the ball to me!' },
    'catch': { pos: 'verb', meaning: '잡다', example: 'I can catch the ball.' },
    'carry': { pos: 'verb', meaning: '나르다', example: 'I carry my books to school.' },
    'drop': { pos: 'verb', meaning: '떨어뜨리다', example: 'I dropped my pencil.' },
    'lift': { pos: 'verb', meaning: '들어올리다', example: 'Help me lift this box.' },
    'move': { pos: 'verb', meaning: '움직이다', example: 'Do not move, stay here!' },
    'ride': { pos: 'verb', meaning: '타다', example: 'I ride my bike to school.' },
    'shake': { pos: 'verb', meaning: '흔들다', example: 'Shake the bottle before you drink.' },
    'slide': { pos: 'verb', meaning: '미끄러지다', example: 'I slide down the slide.' },
    'spin': { pos: 'verb', meaning: '회전하다', example: 'The top spins really fast.' },
    'turn': { pos: 'verb', meaning: '돌다/돌리다', example: 'Turn left at the corner.' },
    'wave': { pos: 'verb', meaning: '흔들다/손 흔들다', example: 'I wave goodbye to my friend.' },
    'ask': { pos: 'verb', meaning: '묻다', example: 'Can I ask a question?' },
    'call': { pos: 'verb', meaning: '전화하다/부르다', example: 'Call me when you get home.' },
    'cry': { pos: 'verb', meaning: '울다', example: 'The baby is crying.' },
    'laugh': { pos: 'verb', meaning: '웃다', example: 'The joke made me laugh.' },
    'shout': { pos: 'verb', meaning: '소리치다', example: 'Do not shout in the library.' },
    'whisper': { pos: 'verb', meaning: '속삭이다', example: 'She whispered a secret to me.' },
    'bake': { pos: 'verb', meaning: '굽다', example: 'We bake cookies together.' },
    'build': { pos: 'verb', meaning: '짓다/만들다', example: 'I build a tower with blocks.' },
    'change': { pos: 'verb', meaning: '바꾸다', example: 'Change your clothes after playing.' },
    'choose': { pos: 'verb', meaning: '고르다', example: 'Choose your favorite color.' },
    'count': { pos: 'verb', meaning: '세다', example: 'I can count to one hundred.' },
    'cut': { pos: 'verb', meaning: '자르다', example: 'Cut the paper with scissors.' },
    'dig': { pos: 'verb', meaning: '파다', example: 'The dog digs a hole.' },
    'feed': { pos: 'verb', meaning: '먹이다', example: 'I feed my fish every day.' },
    'fill': { pos: 'verb', meaning: '채우다', example: 'Fill the cup with water.' },
    'find': { pos: 'verb', meaning: '찾다', example: 'I found my lost toy!' },
    'finish': { pos: 'verb', meaning: '끝내다', example: 'I finished my homework.' },
    'fix': { pos: 'verb', meaning: '고치다', example: 'Dad can fix my bike.' },
    'follow': { pos: 'verb', meaning: '따라가다', example: 'Follow me to the park.' },
    'get': { pos: 'verb', meaning: '얻다/가져오다', example: 'I got a new toy.' },
    'hang': { pos: 'verb', meaning: '걸다', example: 'Hang your coat on the hook.' },
    'hide': { pos: 'verb', meaning: '숨다/숨기다', example: "Let's play hide and seek." },
    'hit': { pos: 'verb', meaning: '치다/때리다', example: 'I hit the ball with a bat.' },
    'hurry': { pos: 'verb', meaning: '서두르다', example: 'Hurry up, we are late!' },
    'invite': { pos: 'verb', meaning: '초대하다', example: 'I invited my friends to my party.' },
    'join': { pos: 'verb', meaning: '함께하다', example: 'Join us for lunch!' },
    'keep': { pos: 'verb', meaning: '유지하다/간직하다', example: 'Keep your room clean.' },
    'leave': { pos: 'verb', meaning: '떠나다', example: 'We leave for school at eight.' },
    'lose': { pos: 'verb', meaning: '잃다/지다', example: 'I do not want to lose.' },
    'meet': { pos: 'verb', meaning: '만나다', example: 'Nice to meet you!' },
    'miss': { pos: 'verb', meaning: '그리워하다/놓치다', example: 'I miss my grandma.' },
    'mix': { pos: 'verb', meaning: '섞다', example: 'Mix the colors together.' },
    'need': { pos: 'verb', meaning: '필요하다', example: 'I need a pencil.' },
    'paint': { pos: 'verb', meaning: '칠하다/그리다', example: 'I paint a picture of the sun.' },
    'pass': { pos: 'verb', meaning: '전달하다/지나가다', example: 'Pass me the salt, please.' },
    'pay': { pos: 'verb', meaning: '지불하다', example: 'Mom pays for the food.' },
    'pick': { pos: 'verb', meaning: '고르다/줍다', example: 'I pick flowers in the garden.' },
    'plan': { pos: 'verb', meaning: '계획하다', example: 'We plan a trip to the zoo.' },
    'point': { pos: 'verb', meaning: '가리키다', example: 'Point to the correct answer.' },
    'pour': { pos: 'verb', meaning: '붓다', example: 'Pour milk into the glass.' },
    'prepare': { pos: 'verb', meaning: '준비하다', example: 'I prepare my bag for school.' },
    'press': { pos: 'verb', meaning: '누르다', example: 'Press the button to start.' },
    'reach': { pos: 'verb', meaning: '닿다/도착하다', example: 'I cannot reach the top shelf.' },
    'remember': { pos: 'verb', meaning: '기억하다', example: 'Remember to bring your book.' },
    'return': { pos: 'verb', meaning: '돌아가다/반납하다', example: 'I return the book to the library.' },
    'save': { pos: 'verb', meaning: '구하다/저축하다', example: 'I save money in my piggy bank.' },
    'search': { pos: 'verb', meaning: '찾다/검색하다', example: 'I search for my lost toy.' },
    'send': { pos: 'verb', meaning: '보내다', example: 'I send a letter to grandma.' },
    'share': { pos: 'verb', meaning: '나누다', example: 'I share my snack with my friend.' },
    'show': { pos: 'verb', meaning: '보여주다', example: 'Show me your drawing!' },
    'smile': { pos: 'verb', meaning: '미소짓다', example: 'She smiles at me every day.' },
    'spell': { pos: 'verb', meaning: '철자하다', example: 'Can you spell your name?' },
    'spend': { pos: 'verb', meaning: '쓰다/보내다', example: 'I spend time with my family.' },
    'stay': { pos: 'verb', meaning: '머무르다', example: 'Stay here and wait for me.' },
    'taste': { pos: 'verb', meaning: '맛보다', example: 'Taste this soup, it is good!' },
    'teach': { pos: 'verb', meaning: '가르치다', example: 'Mom teaches me to cook.' },
    'thank': { pos: 'verb', meaning: '감사하다', example: 'I thank my teacher every day.' },
    'touch': { pos: 'verb', meaning: '만지다', example: 'Do not touch the hot stove.' },
    'use': { pos: 'verb', meaning: '사용하다', example: 'I use a pencil to write.' },
    'visit': { pos: 'verb', meaning: '방문하다', example: 'We visit grandma on Sunday.' },
    'wait': { pos: 'verb', meaning: '기다리다', example: 'Wait for me, please!' },
    'wake': { pos: 'verb', meaning: '깨다/일어나다', example: 'I wake up at seven.' },
    'want': { pos: 'verb', meaning: '원하다', example: 'I want ice cream.' },
    'wear': { pos: 'verb', meaning: '입다', example: 'I wear my new shoes today.' },
    'win': { pos: 'verb', meaning: '이기다', example: 'I want to win the race!' },
    'worry': { pos: 'verb', meaning: '걱정하다', example: 'Do not worry, it will be okay.' },
    'bite': { pos: 'verb', meaning: '물다', example: 'The dog does not bite.' },
    'blow': { pos: 'verb', meaning: '불다', example: 'Blow out the candles!' },
    'break': { pos: 'verb', meaning: '부수다/깨다', example: 'Be careful, do not break the glass.' },
    'burn': { pos: 'verb', meaning: '태우다/타다', example: 'Do not burn your fingers.' },
    'chase': { pos: 'verb', meaning: '쫓다', example: 'The dog chases the cat.' },
    'check': { pos: 'verb', meaning: '확인하다', example: 'Check your answers.' },
    'cheer': { pos: 'verb', meaning: '응원하다', example: 'We cheer for our team.' },
    'collect': { pos: 'verb', meaning: '모으다', example: 'I collect pretty rocks.' },
    'copy': { pos: 'verb', meaning: '베끼다/복사하다', example: 'Copy the words from the board.' },
    'crash': { pos: 'verb', meaning: '충돌하다', example: 'The toy cars crash into each other.' },
    'create': { pos: 'verb', meaning: '만들다/창조하다', example: 'I create art with paint.' },
    'cross': { pos: 'verb', meaning: '건너다', example: 'Cross the street carefully.' },
    'discover': { pos: 'verb', meaning: '발견하다', example: 'I discovered a new bug!' },
    'dry': { pos: 'verb', meaning: '말리다', example: 'Dry your hair with a towel.' },
    'enjoy': { pos: 'verb', meaning: '즐기다', example: 'I enjoy playing with friends.' },
    'enter': { pos: 'verb', meaning: '들어가다', example: 'Please enter the classroom.' },
    'escape': { pos: 'verb', meaning: '탈출하다', example: 'The bird escaped from the cage.' },
    'explain': { pos: 'verb', meaning: '설명하다', example: 'The teacher explains the lesson.' },
    'explore': { pos: 'verb', meaning: '탐험하다', example: 'I explore the forest.' },
    'fear': { pos: 'verb', meaning: '무서워하다', example: 'I fear the dark sometimes.' },
    'fight': { pos: 'verb', meaning: '싸우다', example: 'Do not fight with your brother.' },
    'float': { pos: 'verb', meaning: '뜨다', example: 'The boat floats on the water.' },
    'forget': { pos: 'verb', meaning: '잊다', example: 'Do not forget your homework.' },
    'forgive': { pos: 'verb', meaning: '용서하다', example: 'I forgive you.' },
    'freeze': { pos: 'verb', meaning: '얼다', example: 'Water freezes in winter.' },
    'guess': { pos: 'verb', meaning: '추측하다', example: 'Can you guess the answer?' },
    'happen': { pos: 'verb', meaning: '일어나다', example: 'What happened yesterday?' },
    'hate': { pos: 'verb', meaning: '싫어하다', example: 'I hate getting up early.' },
    'hug': { pos: 'verb', meaning: '안다', example: 'I hug my mom every day.' },
    'imagine': { pos: 'verb', meaning: '상상하다', example: 'Imagine you can fly!' },
    'improve': { pos: 'verb', meaning: '향상시키다', example: 'I improve my English every day.' },
    'knock': { pos: 'verb', meaning: '두드리다', example: 'Knock on the door, please.' },
    'land': { pos: 'verb', meaning: '착륙하다', example: 'The plane lands at the airport.' },
    'lend': { pos: 'verb', meaning: '빌려주다', example: 'Can you lend me a pencil?' },
    'mark': { pos: 'verb', meaning: '표시하다', example: 'Mark the correct answer.' },
    'measure': { pos: 'verb', meaning: '측정하다', example: 'We measure with a ruler.' },
    'melt': { pos: 'verb', meaning: '녹다', example: 'The snow melts in spring.' },
    'notice': { pos: 'verb', meaning: '알아차리다', example: 'I noticed a butterfly.' },
    'order': { pos: 'verb', meaning: '주문하다', example: 'We order food at the restaurant.' },
    'perform': { pos: 'verb', meaning: '공연하다', example: 'I perform in the school play.' },
    'plant': { pos: 'verb', meaning: '심다', example: 'We plant seeds in the garden.' },
    'prefer': { pos: 'verb', meaning: '더 좋아하다', example: 'I prefer milk to juice.' },
    'pretend': { pos: 'verb', meaning: '~인 척하다', example: 'I pretend to be a superhero.' },
    'protect': { pos: 'verb', meaning: '보호하다', example: 'A helmet protects your head.' },
    'race': { pos: 'verb', meaning: '경주하다', example: 'We race to the playground.' },
    'relax': { pos: 'verb', meaning: '쉬다', example: 'I relax after school.' },
    'remind': { pos: 'verb', meaning: '상기시키다', example: 'Remind me to bring my book.' },
    'repair': { pos: 'verb', meaning: '수리하다', example: 'Dad repairs the broken toy.' },
    'repeat': { pos: 'verb', meaning: '반복하다', example: 'Please repeat after me.' },
    'rest': { pos: 'verb', meaning: '쉬다', example: 'I need to rest after running.' },
    'rush': { pos: 'verb', meaning: '급히 가다', example: 'I rush to school every morning.' },
    'scare': { pos: 'verb', meaning: '무섭게 하다', example: 'Spiders scare me.' },
    'scream': { pos: 'verb', meaning: '비명을 지르다', example: 'I scream on the roller coaster.' },
    'sell': { pos: 'verb', meaning: '팔다', example: 'They sell ice cream here.' },
    'shoot': { pos: 'verb', meaning: '쏘다', example: 'I shoot the basketball.' },
    'sink': { pos: 'verb', meaning: '가라앉다', example: 'The rock sinks in the water.' },
    'skip': { pos: 'verb', meaning: '건너뛰다/스킵하다', example: 'I skip down the path.' },
    'solve': { pos: 'verb', meaning: '풀다/해결하다', example: 'I can solve the puzzle.' },
    'steal': { pos: 'verb', meaning: '훔치다', example: 'It is wrong to steal.' },
    'stretch': { pos: 'verb', meaning: '스트레칭하다', example: 'Stretch your arms up high.' },
    'succeed': { pos: 'verb', meaning: '성공하다', example: 'If you try hard, you will succeed.' },
    'support': { pos: 'verb', meaning: '응원하다/지지하다', example: 'My family supports me.' },
    'sweep': { pos: 'verb', meaning: '쓸다', example: 'I sweep the floor.' },
    'tie': { pos: 'verb', meaning: '묶다', example: 'I tie my shoelaces.' },
    'train': { pos: 'verb', meaning: '훈련하다', example: 'I train for the race.' },
    'travel': { pos: 'verb', meaning: '여행하다', example: 'We travel to Japan.' },
    'trust': { pos: 'verb', meaning: '믿다', example: 'I trust my best friend.' },
    'understand': { pos: 'verb', meaning: '이해하다', example: 'I understand the question.' },
    'welcome': { pos: 'verb', meaning: '환영하다', example: 'Welcome to our school!' },
    'wonder': { pos: 'verb', meaning: '궁금하다', example: 'I wonder why the sky is blue.' },
    'wrap': { pos: 'verb', meaning: '포장하다', example: 'I wrap a gift for my friend.' },
    // ===== MORE ADJECTIVES =====
    'angry': { pos: 'adjective', meaning: '화난', example: 'Do not be angry at me.' },
    'afraid': { pos: 'adjective', meaning: '무서운/두려운', example: 'I am afraid of the dark.' },
    'alone': { pos: 'adjective', meaning: '혼자인', example: 'I do not like being alone.' },
    'amazing': { pos: 'adjective', meaning: '놀라운', example: 'The show was amazing!' },
    'awful': { pos: 'adjective', meaning: '끔찍한', example: 'The weather is awful today.' },
    'blind': { pos: 'adjective', meaning: '눈이 안 보이는', example: 'The blind man has a guide dog.' },
    'bored': { pos: 'adjective', meaning: '지루한', example: 'I am bored, let us play.' },
    'broken': { pos: 'adjective', meaning: '부서진', example: 'My toy is broken.' },
    'brown': { pos: 'adjective', meaning: '갈색의', example: 'I have brown eyes.' },
    'busy': { pos: 'adjective', meaning: '바쁜', example: 'Mom is very busy today.' },
    'calm': { pos: 'adjective', meaning: '차분한', example: 'Stay calm and breathe.' },
    'careful': { pos: 'adjective', meaning: '조심하는', example: 'Be careful with scissors.' },
    'cheap': { pos: 'adjective', meaning: '싼', example: 'This pencil is cheap.' },
    'clear': { pos: 'adjective', meaning: '맑은/분명한', example: 'The water is very clear.' },
    'clever': { pos: 'adjective', meaning: '영리한', example: 'The fox is very clever.' },
    'comfortable': { pos: 'adjective', meaning: '편안한', example: 'This chair is comfortable.' },
    'cool': { pos: 'adjective', meaning: '시원한/멋진', example: 'Your new shoes are so cool!' },
    'correct': { pos: 'adjective', meaning: '맞는/올바른', example: 'Your answer is correct!' },
    'crazy': { pos: 'adjective', meaning: '미친/엄청난', example: 'That was a crazy ride!' },
    'curious': { pos: 'adjective', meaning: '궁금한', example: 'I am curious about space.' },
    'cute': { pos: 'adjective', meaning: '귀여운', example: 'The puppy is so cute!' },
    'dangerous': { pos: 'adjective', meaning: '위험한', example: 'Fire can be dangerous.' },
    'dead': { pos: 'adjective', meaning: '죽은', example: 'The flower is dead.' },
    'deep': { pos: 'adjective', meaning: '깊은', example: 'The ocean is very deep.' },
    'delicious': { pos: 'adjective', meaning: '맛있는', example: 'This cake is delicious!' },
    'different': { pos: 'adjective', meaning: '다른', example: 'We are all different.' },
    'dry': { pos: 'adjective', meaning: '마른/건조한', example: 'The towel is dry.' },
    'empty': { pos: 'adjective', meaning: '빈', example: 'The box is empty.' },
    'excited': { pos: 'adjective', meaning: '흥분된/신나는', example: 'I am excited about the trip!' },
    'expensive': { pos: 'adjective', meaning: '비싼', example: 'The toy is too expensive.' },
    'fair': { pos: 'adjective', meaning: '공정한', example: 'That is not fair!' },
    'famous': { pos: 'adjective', meaning: '유명한', example: 'She is a famous singer.' },
    'favorite': { pos: 'adjective', meaning: '가장 좋아하는', example: 'Blue is my favorite color.' },
    'flat': { pos: 'adjective', meaning: '평평한', example: 'The road is flat.' },
    'free': { pos: 'adjective', meaning: '자유로운/무료의', example: 'The bird is free.' },
    'fresh': { pos: 'adjective', meaning: '신선한', example: 'The bread is fresh.' },
    'friendly': { pos: 'adjective', meaning: '다정한', example: 'My neighbor is very friendly.' },
    'frozen': { pos: 'adjective', meaning: '얼어붙은', example: 'The lake is frozen in winter.' },
    'full': { pos: 'adjective', meaning: '가득 찬/배부른', example: 'My stomach is full.' },
    'gentle': { pos: 'adjective', meaning: '부드러운/온화한', example: 'Be gentle with the kitten.' },
    'giant': { pos: 'adjective', meaning: '거대한', example: 'I saw a giant pumpkin.' },
    'golden': { pos: 'adjective', meaning: '금빛의', example: 'The sunset is golden.' },
    'great': { pos: 'adjective', meaning: '대단한/멋진', example: 'You did a great job!' },
    'handsome': { pos: 'adjective', meaning: '잘생긴', example: 'The prince is handsome.' },
    'healthy': { pos: 'adjective', meaning: '건강한', example: 'Eat healthy food.' },
    'heavy': { pos: 'adjective', meaning: '무거운', example: 'This bag is very heavy.' },
    'helpful': { pos: 'adjective', meaning: '도움이 되는', example: 'She is very helpful.' },
    'honest': { pos: 'adjective', meaning: '정직한', example: 'Always be honest.' },
    'horrible': { pos: 'adjective', meaning: '끔찍한', example: 'The weather was horrible.' },
    'huge': { pos: 'adjective', meaning: '거대한', example: 'The whale is huge!' },
    'icy': { pos: 'adjective', meaning: '얼음 같은', example: 'The road is icy today.' },
    'interested': { pos: 'adjective', meaning: '관심 있는', example: 'I am interested in science.' },
    'jealous': { pos: 'adjective', meaning: '질투하는', example: 'Do not be jealous.' },
    'large': { pos: 'adjective', meaning: '큰', example: 'I want a large pizza.' },
    'late': { pos: 'adjective', meaning: '늦은', example: 'I am late for school.' },
    'lazy': { pos: 'adjective', meaning: '게으른', example: 'The lazy cat sleeps all day.' },
    'light': { pos: 'adjective', meaning: '가벼운/밝은', example: 'The feather is very light.' },
    'lonely': { pos: 'adjective', meaning: '외로운', example: 'I feel lonely without friends.' },
    'lucky': { pos: 'adjective', meaning: '운이 좋은', example: 'I am so lucky today!' },
    'mad': { pos: 'adjective', meaning: '화난', example: 'Mom is mad because I lied.' },
    'mean': { pos: 'adjective', meaning: '못된', example: 'Do not be mean to others.' },
    'messy': { pos: 'adjective', meaning: '지저분한', example: 'My room is messy.' },
    'narrow': { pos: 'adjective', meaning: '좁은', example: 'The path is very narrow.' },
    'neat': { pos: 'adjective', meaning: '깔끔한', example: 'Your handwriting is neat.' },
    'nervous': { pos: 'adjective', meaning: '긴장되는', example: 'I am nervous before the test.' },
    'nice': { pos: 'adjective', meaning: '좋은/친절한', example: 'She is a nice girl.' },
    'normal': { pos: 'adjective', meaning: '보통의', example: 'It is normal to make mistakes.' },
    'pale': { pos: 'adjective', meaning: '창백한', example: 'You look pale, are you okay?' },
    'patient': { pos: 'adjective', meaning: '참을성 있는', example: 'Be patient, it takes time.' },
    'perfect': { pos: 'adjective', meaning: '완벽한', example: 'Your drawing is perfect!' },
    'polite': { pos: 'adjective', meaning: '예의 바른', example: 'Always be polite to adults.' },
    'poor': { pos: 'adjective', meaning: '가난한/불쌍한', example: 'Poor puppy, it is raining.' },
    'possible': { pos: 'adjective', meaning: '가능한', example: 'Anything is possible!' },
    'powerful': { pos: 'adjective', meaning: '강력한', example: 'The superhero is powerful.' },
    'proud': { pos: 'adjective', meaning: '자랑스러운', example: 'I am proud of you!' },
    'ready': { pos: 'adjective', meaning: '준비된', example: 'Are you ready to go?' },
    'real': { pos: 'adjective', meaning: '진짜의', example: 'Is that a real diamond?' },
    'rich': { pos: 'adjective', meaning: '부자인', example: 'The king is very rich.' },
    'round': { pos: 'adjective', meaning: '둥근', example: 'The ball is round.' },
    'rude': { pos: 'adjective', meaning: '무례한', example: 'It is rude to interrupt.' },
    'safe': { pos: 'adjective', meaning: '안전한', example: 'Stay safe on the road.' },
    'salty': { pos: 'adjective', meaning: '짠', example: 'The soup is too salty.' },
    'scary': { pos: 'adjective', meaning: '무서운', example: 'The movie was scary.' },
    'selfish': { pos: 'adjective', meaning: '이기적인', example: 'Do not be selfish, share!' },
    'serious': { pos: 'adjective', meaning: '심각한/진지한', example: 'This is a serious problem.' },
    'sharp': { pos: 'adjective', meaning: '날카로운', example: 'The knife is sharp.' },
    'shiny': { pos: 'adjective', meaning: '빛나는', example: 'The star is shiny.' },
    'shy': { pos: 'adjective', meaning: '수줍은', example: 'The cat is shy.' },
    'sick': { pos: 'adjective', meaning: '아픈', example: 'I am sick today.' },
    'silly': { pos: 'adjective', meaning: '바보 같은/우스운', example: 'You are so silly!' },
    'simple': { pos: 'adjective', meaning: '간단한', example: 'The question is simple.' },
    'skinny': { pos: 'adjective', meaning: '마른', example: 'The cat is very skinny.' },
    'smart': { pos: 'adjective', meaning: '똑똑한', example: 'She is a smart girl.' },
    'smooth': { pos: 'adjective', meaning: '매끄러운', example: 'The rock is smooth.' },
    'sour': { pos: 'adjective', meaning: '신', example: 'The lemon is sour.' },
    'steep': { pos: 'adjective', meaning: '가파른', example: 'The hill is very steep.' },
    'sticky': { pos: 'adjective', meaning: '끈적한', example: 'My hands are sticky.' },
    'strange': { pos: 'adjective', meaning: '이상한', example: 'I heard a strange noise.' },
    'stupid': { pos: 'adjective', meaning: '멍청한', example: 'That was a stupid mistake.' },
    'sudden': { pos: 'adjective', meaning: '갑작스러운', example: 'There was a sudden loud noise.' },
    'surprised': { pos: 'adjective', meaning: '놀란', example: 'I was surprised by the gift.' },
    'terrible': { pos: 'adjective', meaning: '끔찍한', example: 'The storm was terrible.' },
    'thick': { pos: 'adjective', meaning: '두꺼운', example: 'This is a thick book.' },
    'thin': { pos: 'adjective', meaning: '얇은', example: 'The paper is very thin.' },
    'thirsty': { pos: 'adjective', meaning: '목마른', example: 'I am thirsty after running.' },
    'tight': { pos: 'adjective', meaning: '꽉 끼는', example: 'These shoes are too tight.' },
    'tiny': { pos: 'adjective', meaning: '아주 작은', example: 'The baby bird is tiny.' },
    'tough': { pos: 'adjective', meaning: '힘든/질긴', example: 'That was a tough game.' },
    'ugly': { pos: 'adjective', meaning: '못생긴', example: 'The monster looks ugly.' },
    'useful': { pos: 'adjective', meaning: '유용한', example: 'This tool is very useful.' },
    'warm': { pos: 'adjective', meaning: '따뜻한', example: 'The blanket is warm.' },
    'weak': { pos: 'adjective', meaning: '약한', example: 'The baby bird is weak.' },
    'wet': { pos: 'adjective', meaning: '젖은', example: 'My clothes are wet from the rain.' },
    'wide': { pos: 'adjective', meaning: '넓은', example: 'The river is very wide.' },
    'wild': { pos: 'adjective', meaning: '야생의', example: 'Wild animals live in the forest.' },
    'wise': { pos: 'adjective', meaning: '현명한', example: 'The owl is wise.' },
    'wonderful': { pos: 'adjective', meaning: '멋진/훌륭한', example: 'We had a wonderful time.' },
    'worried': { pos: 'adjective', meaning: '걱정하는', example: 'Mom is worried about me.' },
    'wrong': { pos: 'adjective', meaning: '틀린', example: 'That answer is wrong.' },
    'young': { pos: 'adjective', meaning: '어린', example: 'She is young and strong.' },
    'pink': { pos: 'adjective', meaning: '분홍색의', example: 'She likes pink flowers.' },
    'purple': { pos: 'adjective', meaning: '보라색의', example: 'I see purple grapes.' },
    'gray': { pos: 'adjective', meaning: '회색의', example: 'The sky is gray today.' },
    'orange': { pos: 'adjective', meaning: '주황색의', example: 'The sunset is orange.' },
    // ===== MORE ADVERBS =====
    'carefully': { pos: 'adverb', meaning: '조심히', example: 'Walk carefully on the ice.' },
    'easily': { pos: 'adverb', meaning: '쉽게', example: 'I can do this easily.' },
    'finally': { pos: 'adverb', meaning: '마침내', example: 'I finally finished my homework!' },
    'gently': { pos: 'adverb', meaning: '부드럽게', example: 'Pet the cat gently.' },
    'happily': { pos: 'adverb', meaning: '행복하게', example: 'She smiled happily.' },
    'honestly': { pos: 'adverb', meaning: '솔직히', example: 'Honestly, I do not know.' },
    'kindly': { pos: 'adverb', meaning: '친절하게', example: 'She spoke kindly to me.' },
    'loudly': { pos: 'adverb', meaning: '크게', example: 'He laughed loudly.' },
    'nicely': { pos: 'adverb', meaning: '잘/멋지게', example: 'You sing very nicely.' },
    'perfectly': { pos: 'adverb', meaning: '완벽하게', example: 'She dances perfectly.' },
    'politely': { pos: 'adverb', meaning: '예의바르게', example: 'Ask politely, please.' },
    'quietly': { pos: 'adverb', meaning: '조용히', example: 'Walk quietly in the library.' },
    'sadly': { pos: 'adverb', meaning: '슬프게', example: 'She looked at me sadly.' },
    'safely': { pos: 'adverb', meaning: '안전하게', example: 'We arrived home safely.' },
    'seriously': { pos: 'adverb', meaning: '진지하게', example: 'I am seriously hungry.' },
    'softly': { pos: 'adverb', meaning: '부드럽게', example: 'She spoke softly to the baby.' },
    'suddenly': { pos: 'adverb', meaning: '갑자기', example: 'Suddenly, it started to rain.' },
    'surely': { pos: 'adverb', meaning: '확실히', example: 'You can surely do it!' },
    'truly': { pos: 'adverb', meaning: '정말로', example: 'I am truly sorry.' },
    'wisely': { pos: 'adverb', meaning: '현명하게', example: 'Use your time wisely.' },
    'early': { pos: 'adverb', meaning: '일찍', example: 'I wake up early.' },
    'late': { pos: 'adverb', meaning: '늦게', example: 'Do not stay up late.' },
    'now': { pos: 'adverb', meaning: '지금', example: 'Let us go now.' },
    'soon': { pos: 'adverb', meaning: '곧', example: 'We will arrive soon.' },
    'sometimes': { pos: 'adverb', meaning: '가끔', example: 'I sometimes eat chocolate.' },
    'usually': { pos: 'adverb', meaning: '보통', example: 'I usually sleep at nine.' },
    'recently': { pos: 'adverb', meaning: '최근에', example: 'I recently got a new bike.' },
    'immediately': { pos: 'adverb', meaning: '즉시', example: 'Come here immediately!' },
    'eventually': { pos: 'adverb', meaning: '결국', example: 'We eventually found the dog.' },
    'above': { pos: 'adverb', meaning: '위에', example: 'The bird flies above us.' },
    'away': { pos: 'adverb', meaning: '멀리', example: 'Go away, I am busy!' },
    'behind': { pos: 'adverb', meaning: '뒤에', example: 'The cat is hiding behind the sofa.' },
    'below': { pos: 'adverb', meaning: '아래에', example: 'The fish swims below the boat.' },
    'down': { pos: 'adverb', meaning: '아래로', example: 'Sit down, please.' },
    'everywhere': { pos: 'adverb', meaning: '어디에나', example: 'I looked everywhere for my keys.' },
    'far': { pos: 'adverb', meaning: '멀리', example: 'The school is not far.' },
    'forward': { pos: 'adverb', meaning: '앞으로', example: 'Take one step forward.' },
    'nearby': { pos: 'adverb', meaning: '근처에', example: 'The park is nearby.' },
    'somewhere': { pos: 'adverb', meaning: '어딘가에', example: 'I left my book somewhere.' },
    'up': { pos: 'adverb', meaning: '위로', example: 'Look up at the stars!' },
    'upstairs': { pos: 'adverb', meaning: '위층으로', example: 'My room is upstairs.' },
    'downstairs': { pos: 'adverb', meaning: '아래층으로', example: 'Come downstairs for dinner.' },
    'almost': { pos: 'adverb', meaning: '거의', example: 'I am almost done!' },
    'enough': { pos: 'adverb', meaning: '충분히', example: 'I have eaten enough.' },
    'especially': { pos: 'adverb', meaning: '특히', example: 'I love fruit, especially grapes.' },
    'even': { pos: 'adverb', meaning: '심지어', example: 'Even my dog likes music.' },
    'exactly': { pos: 'adverb', meaning: '정확히', example: 'That is exactly right!' },
    'extremely': { pos: 'adverb', meaning: '매우/극도로', example: 'It is extremely cold today.' },
    'quite': { pos: 'adverb', meaning: '꽤', example: 'The movie was quite good.' },
    'too': { pos: 'adverb', meaning: '너무/또한', example: 'This is too hot to eat.' },
    'totally': { pos: 'adverb', meaning: '완전히', example: 'I totally agree with you.' },
    'completely': { pos: 'adverb', meaning: '완전히', example: 'I completely forgot!' },
    'probably': { pos: 'adverb', meaning: '아마', example: 'It will probably rain today.' },
    'maybe': { pos: 'adverb', meaning: '아마도', example: 'Maybe we can go tomorrow.' },
    'only': { pos: 'adverb', meaning: '단지/오직', example: 'I have only one sister.' },
    'once': { pos: 'adverb', meaning: '한 번', example: 'I go to the dentist once a year.' },
    'twice': { pos: 'adverb', meaning: '두 번', example: 'I brush my teeth twice a day.' },
    'daily': { pos: 'adverb', meaning: '매일', example: 'I exercise daily.' },
    'rarely': { pos: 'adverb', meaning: '거의 안', example: 'I rarely eat candy.' },
    'forever': { pos: 'adverb', meaning: '영원히', example: 'We will be friends forever.' }
  };

  function guessPOS(word) {
    var w = word.toLowerCase();
    if (w.endsWith('ly')) return 'adverb';
    if (w.endsWith('ful') || w.endsWith('ous') || w.endsWith('ive') || w.endsWith('ish') || w.endsWith('able')) return 'adjective';
    if (w.endsWith('tion') || w.endsWith('sion') || w.endsWith('ment') || w.endsWith('ness') || w.endsWith('ity')) return 'noun';
    if (w.endsWith('ing') || w.endsWith('ed') || w.endsWith('ize') || w.endsWith('ate')) return 'verb';
    return '';
  }

  function lookupDict(word) {
    return DICT[word.toLowerCase()] || null;
  }

  function callAPI(messages) {
    var settings = App.getSettings();
    if (!settings.aiEnabled) return Promise.resolve(null);

    var provider = settings.aiProvider || 'gemini';
    var url = provider === 'claude' ? API_URL_CLAUDE : API_URL_GEMINI;

    return fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ messages: messages, max_tokens: 300 })
    })
    .then(function(resp) {
      if (!resp.ok) return null;
      return resp.json();
    })
    .then(function(data) {
      if (!data || data.error) return null;
      return (data.content && data.content[0] && data.content[0].text) || null;
    })
    .catch(function(e) {
      console.log('API call failed:', e);
      return null;
    });
  }

  function getWordInfo(word) {
    // Try dictionary first (instant, no network needed)
    var fb = lookupDict(word);
    if (fb) {
      return Promise.resolve({ meaning: fb.meaning, pos: fb.pos, example: fb.example });
    }

    // Try API
    var prompt = 'For the English word "' + word + '", provide in JSON format:\n{"meaning": "Korean meaning", "pos": "noun/verb/adjective/adverb", "example": "Simple example sentence for a child"}\nReply ONLY with the JSON, no extra text.';

    return callAPI([{ role: 'user', content: prompt }])
      .then(function(text) {
        if (text) {
          try {
            var match = text.match(/\{[\s\S]*\}/);
            if (match) return JSON.parse(match[0]);
          } catch(e) { /* ignore parse errors */ }
        }
        // Last resort - guess POS
        return { meaning: '', pos: guessPOS(word), example: '' };
      });
  }

  function getSpellingHint(word, meaning) {
    var prompt = 'Give a fun, one-sentence spelling hint for the word "' + word + '" (meaning: ' + (meaning || word) + '). Keep it simple for a child. Reply with just the hint.';
    return callAPI([{ role: 'user', content: prompt }])
      .then(function(text) {
        return text || 'This word has ' + word.length + ' letters and starts with "' + word[0].toUpperCase() + '"!';
      });
  }

  function getSentenceExample(word, meaning) {
    var fb = lookupDict(word);
    if (fb && fb.example) return Promise.resolve(fb.example);

    var prompt = 'Write a simple example sentence using the word "' + word + '". Easy for a child age 7-9. Reply with just the sentence.';
    return callAPI([{ role: 'user', content: prompt }])
      .then(function(text) {
        return text || 'I like the word ' + word + '.';
      });
  }

  function getSentenceStarter(word, meaning) {
    var prompt = 'Start a sentence using the word "' + word + '" but leave it incomplete for a child to finish. Reply with just the starter.';
    return callAPI([{ role: 'user', content: prompt }])
      .then(function(text) {
        return text || 'The ' + word + '...';
      });
  }

  function reviewSentence(word, sentence) {
    var prompt = 'A child (age 7-9) wrote this sentence using "' + word + '": "' + sentence + '"\nGive brief, encouraging feedback. Be very positive. Reply in English and Korean mix.';
    return callAPI([{ role: 'user', content: prompt }])
      .then(function(text) {
        return text || null;
      });
  }

  function getFallbackPOS(word) {
    var fb = lookupDict(word);
    if (fb) return fb.pos;
    return guessPOS(word);
  }

  return {
    getWordInfo: getWordInfo,
    getSpellingHint: getSpellingHint,
    getSentenceExample: getSentenceExample,
    getSentenceStarter: getSentenceStarter,
    reviewSentence: reviewSentence,
    getFallbackPOS: getFallbackPOS,
    lookupDict: lookupDict
  };
})();

console.log('AI module loaded:', typeof AI === 'object' ? 'OK' : 'FAILED');
